import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e1e3e4",
        "primary-fixed": "#ffdad4",
        "tertiary-container": "#434242",
        "tertiary": "#2c2c2c",
        "on-primary-fixed-variant": "#920703",
        "surface-variant": "#dbe4ed",
        "on-secondary-container": "#626566",
        "inverse-primary": "#ffb4a8",
        "tertiary-fixed-dim": "#c8c6c5",
        "outline-variant": "#e3beb8",
        "on-error": "#ffffff",
        "surface-container-high": "#e0e9f2",
        "surface-container": "#e6eff8",
        "primary-fixed-dim": "#ffb4a8",
        "primary-container": "#8b0000",
        "secondary-fixed-dim": "#c5c7c8",
        "on-tertiary-fixed-variant": "#474746",
        "on-tertiary-container": "#b1aeae",
        "surface-dim": "#d2dbe4",
        "surface-tint": "#b52619",
        "surface-container-low": "#ecf5fe",
        "secondary-fixed": "#e1e3e4",
        "on-tertiary-fixed": "#1c1b1b",
        "inverse-on-surface": "#e9f2fb",
        "error-container": "#ffdad6",
        "secondary": "#5c5f60",
        "on-background": "#141d23",
        "surface-container-highest": "#dbe4ed",
        "background": "#f6faff",
        "on-primary-container": "#ff907f",
        "primary": "#610000",
        "on-primary-fixed": "#410000",
        "surface-bright": "#f6faff",
        "surface": "#f6faff",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary-fixed-variant": "#454748",
        "on-surface-variant": "#5a403c",
        "inverse-surface": "#293138",
        "outline": "#8e706b",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#191c1d",
        "on-surface": "#141d23",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "48px",
        unit: "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "label-sm": ["var(--font-hanken)", "sans-serif"],
        "label-bold": ["var(--font-hanken)", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "headline-display": ["var(--font-montserrat)", "sans-serif"],
        "headline-md": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
